name 'thias-skel'
version '0.1.1'
source 'git://github.com/thias/puppet-modules/modules/skel'
author 'Matthias Saou'
license 'Apache 2.0'
summary 'Skeleton module'
description "Install, enable and configure bla bla bla."
project_page 'http://glee.thias.es/puppet'
