name 'thias-skel'
version '0.1.0'
source 'git://github.com/thias/puppet-skel'
author 'Matthias Saou'
license 'Apache 2.0'
summary 'Skeleton module'
description "Install, enable and configure bla bla bla."
project_page 'https://github.com/thias/puppet-skel'
