name 'thias-mysql'
version '0.1.1'
source 'git://github.com/thias/puppet-modules/modules/mysql'
author 'Matthias Saou'
license 'Apache 2.0'
summary 'MySQL Server module'
description "Install, enable and configure MySQL Server."
project_page 'http://glee.thias.es/puppet'
