name 'thias-cosmetic'
version '0.1.4'
source 'git://github.com/thias/puppet-modules/modules/cosmetic'
author 'Matthias Saou'
license 'Apache 2.0'
summary 'Cosmetic changes module'
description "Cosmetic Operating System related changes : Bash prompt, MOTD, etc."
project_page 'http://glee.thias.es/puppet'
